fn function {
  next # error: Syntax error at "next": Can't use 'next' outside of a loop.
}

next # error: Syntax error at "next": Can't use 'next' outside of a loop.

while true {
  fn foo {
    next # error: Syntax error at "next": Can't use 'next' outside of a loop.
  }
}
